# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      "GitHub Actions updates":
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/php/php74"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/php/php80"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/php/php81"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/php/php82"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/php/php83"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/apache"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/mysql"
    schedule:
      interval: "monthly"