volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  bitrixdock:

services:
  php:
    build: ./${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
    restart: on-failure
  web_server:
    build: ./${WEB_SERVER_TYPE}
    container_name: ${COMPOSE_PROJECT_NAME}_web_server
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:80:80'
      - '${INTERFACE}:443:443'
    links:
      - php
    networks:
      - bitrixdock
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: on-failure
  cron:
    build:
      context: ./cron
      args:
        - PHP_VERSION=${CRON_PHP_VERSION}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${COMPOSE_PROJECT_NAME}_cron
    user: "www-data:www-data"
    entrypoint: [ "sh", "-c", "crond -f" ]
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
    restart: on-failure
  db:
    build: ./${DB_SERVER_TYPE}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    volumes:
      - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Moscow
    command: mysqld --user=root --sql-mode=""
    networks:
      - bitrixdock
    stdin_open: true
    tty: true
    restart: on-failure
  memcached:
    image: memcached:latest
    container_name: ${COMPOSE_PROJECT_NAME}_memcached
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:11211:11211'
    networks:
      - bitrixdock
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    links:
      - db:db
    ports:
      - '${INTERFACE}:8080:80'
    environment:
      UPLOAD: 1024M # upload_max_filesize, post_max_size
      TZ: Europe/Moscow
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
  mailhog:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    restart: on-failure
    ports:
      - '${INTERFACE}:1025:1025'
      - '${INTERFACE}:8025:8025'
    networks:
      - bitrixdock
  source:
    image: alpine:latest
    container_name: ${COMPOSE_PROJECT_NAME}_source
    volumes:
      - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
      - ./logs/php:/var/log/php
      - ./logs/db:/var/log/mysql
      - ./logs/memcached:/var/log/memcached
      - ./logs/mailhog:/var/log/mailhog
      - ./logs/cron:/var/log/cron
      - db:/var/lib/mysql
      - cache:/var/lib/memcached
      - ${SITE_PATH}:/var/www/bitrix
      - /etc/localtime:/etc/localtime/:ro
    networks:
      - bitrixdock
